pypi:
  build: pypi
  volumes:
  - /data01/pypi:/pypi
nginx:
  image: nginx    
  links:
  - pypi
  volumes:
  - ./nginx/html:/usr/share/nginx/html/                                           # default web site home page

  - ./pypi/conf/nginx.server.conf:/etc/nginx/conf.d/pypi.conf                     # pypi server proxy
                                                                                  # note that the data volume is configured in the pypi instance

  - ./rpms/conf/nginx.server.conf:/etc/nginx/conf.d/rpms.conf                     # rpms server
  - /data01/rpms:/rpms/                                                           # rpms server www root

  - ./fwstaging-int/conf/nginx.server.conf:/etc/nginx/conf.d/fwstaging-int.conf   # fwstaging-int server
  - /data01/fwstaging-int:/fwstaging-int/                                                  # fwstaging-int server www root
  ports:
  - 80:80

