# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace.ui'
#
# Created: Tue Mar 27 15:35:32 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Replace(object):
    def setupUi(self, Replace):
        Replace.setObjectName(_fromUtf8("Replace"))
        Replace.setWindowModality(QtCore.Qt.NonModal)
        Replace.resize(490, 240)
        Replace.setMinimumSize(QtCore.QSize(490, 240))
        Replace.setMaximumSize(QtCore.QSize(490, 240))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(10)
        Replace.setFont(font)
        self.groupBox_startpos = QtGui.QGroupBox(Replace)
        self.groupBox_startpos.setGeometry(QtCore.QRect(280, 90, 91, 80))
        self.groupBox_startpos.setObjectName(_fromUtf8("groupBox_startpos"))
        self.radioButton_top = QtGui.QRadioButton(self.groupBox_startpos)
        self.radioButton_top.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.radioButton_top.setChecked(True)
        self.radioButton_top.setObjectName(_fromUtf8("radioButton_top"))
        self.radioButton_bottom = QtGui.QRadioButton(self.groupBox_startpos)
        self.radioButton_bottom.setGeometry(QtCore.QRect(10, 50, 81, 23))
        self.radioButton_bottom.setObjectName(_fromUtf8("radioButton_bottom"))
        self.label_replace = QtGui.QLabel(Replace)
        self.label_replace.setGeometry(QtCore.QRect(11, 50, 101, 26))
        self.label_replace.setObjectName(_fromUtf8("label_replace"))
        self.label_find = QtGui.QLabel(Replace)
        self.label_find.setGeometry(QtCore.QRect(11, 11, 41, 26))
        self.label_find.setObjectName(_fromUtf8("label_find"))
        self.groupBox_mode = QtGui.QGroupBox(Replace)
        self.groupBox_mode.setGeometry(QtCore.QRect(10, 90, 121, 80))
        self.groupBox_mode.setObjectName(_fromUtf8("groupBox_mode"))
        self.radioButton_normal = QtGui.QRadioButton(self.groupBox_mode)
        self.radioButton_normal.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.radioButton_normal.setChecked(True)
        self.radioButton_normal.setObjectName(_fromUtf8("radioButton_normal"))
        self.radioButton_reference = QtGui.QRadioButton(self.groupBox_mode)
        self.radioButton_reference.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.radioButton_reference.setObjectName(_fromUtf8("radioButton_reference"))
        self.groupBox_findops = QtGui.QGroupBox(Replace)
        self.groupBox_findops.setGeometry(QtCore.QRect(140, 90, 121, 81))
        self.groupBox_findops.setObjectName(_fromUtf8("groupBox_findops"))
        self.radioButton_current = QtGui.QRadioButton(self.groupBox_findops)
        self.radioButton_current.setGeometry(QtCore.QRect(10, 20, 111, 23))
        self.radioButton_current.setChecked(True)
        self.radioButton_current.setObjectName(_fromUtf8("radioButton_current"))
        self.radioButton_selection = QtGui.QRadioButton(self.groupBox_findops)
        self.radioButton_selection.setGeometry(QtCore.QRect(10, 50, 93, 23))
        self.radioButton_selection.setObjectName(_fromUtf8("radioButton_selection"))
        self.layoutWidget = QtGui.QWidget(Replace)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 10, 101, 212))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.pushButton_findnext = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_findnext.setDefault(True)
        self.pushButton_findnext.setObjectName(_fromUtf8("pushButton_findnext"))
        self.vboxlayout.addWidget(self.pushButton_findnext)
        self.pushButton_findprev = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_findprev.setObjectName(_fromUtf8("pushButton_findprev"))
        self.vboxlayout.addWidget(self.pushButton_findprev)
        self.pushButton_replace = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_replace.setEnabled(True)
        self.pushButton_replace.setObjectName(_fromUtf8("pushButton_replace"))
        self.vboxlayout.addWidget(self.pushButton_replace)
        self.pushButton_replaceall = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_replaceall.setEnabled(True)
        self.pushButton_replaceall.setObjectName(_fromUtf8("pushButton_replaceall"))
        self.vboxlayout.addWidget(self.pushButton_replaceall)
        self.pushButton_count = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_count.setObjectName(_fromUtf8("pushButton_count"))
        self.vboxlayout.addWidget(self.pushButton_count)
        self.pushButton_findinfiles = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_findinfiles.setObjectName(_fromUtf8("pushButton_findinfiles"))
        self.vboxlayout.addWidget(self.pushButton_findinfiles)
        self.groupBox_options = QtGui.QGroupBox(Replace)
        self.groupBox_options.setGeometry(QtCore.QRect(10, 180, 351, 51))
        self.groupBox_options.setObjectName(_fromUtf8("groupBox_options"))
        self.checkBox_verbatim = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_verbatim.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.checkBox_verbatim.setChecked(True)
        self.checkBox_verbatim.setObjectName(_fromUtf8("checkBox_verbatim"))
        self.checkBox_case = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_case.setGeometry(QtCore.QRect(190, 20, 61, 23))
        self.checkBox_case.setObjectName(_fromUtf8("checkBox_case"))
        self.checkBox_wrap = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_wrap.setGeometry(QtCore.QRect(110, 20, 71, 23))
        self.checkBox_wrap.setObjectName(_fromUtf8("checkBox_wrap"))
        self.checkBox_re = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_re.setGeometry(QtCore.QRect(260, 20, 81, 20))
        self.checkBox_re.setObjectName(_fromUtf8("checkBox_re"))
        self.comboBox_find = QtGui.QComboBox(Replace)
        self.comboBox_find.setGeometry(QtCore.QRect(80, 10, 271, 29))
        self.comboBox_find.setEditable(True)
        self.comboBox_find.setObjectName(_fromUtf8("comboBox_find"))
        self.comboBox_replace = QtGui.QComboBox(Replace)
        self.comboBox_replace.setEnabled(True)
        self.comboBox_replace.setGeometry(QtCore.QRect(130, 50, 221, 29))
        self.comboBox_replace.setEditable(True)
        self.comboBox_replace.setMaxVisibleItems(20)
        self.comboBox_replace.setObjectName(_fromUtf8("comboBox_replace"))

        self.retranslateUi(Replace)
        QtCore.QObject.connect(self.pushButton_findnext, QtCore.SIGNAL(_fromUtf8("clicked()")), Replace.update)
        QtCore.QObject.connect(self.pushButton_findprev, QtCore.SIGNAL(_fromUtf8("clicked()")), Replace.update)
        QtCore.QObject.connect(self.pushButton_count, QtCore.SIGNAL(_fromUtf8("clicked()")), Replace.update)
        QtCore.QObject.connect(self.pushButton_findinfiles, QtCore.SIGNAL(_fromUtf8("clicked()")), Replace.update)
        QtCore.QObject.connect(self.radioButton_current, QtCore.SIGNAL(_fromUtf8("clicked()")), Replace.update)
        QtCore.QObject.connect(self.radioButton_selection, QtCore.SIGNAL(_fromUtf8("clicked()")), Replace.update)
        QtCore.QMetaObject.connectSlotsByName(Replace)

    def retranslateUi(self, Replace):
        Replace.setWindowTitle(QtGui.QApplication.translate("Replace", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_startpos.setTitle(QtGui.QApplication.translate("Replace", "Start From", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_top.setToolTip(QtGui.QApplication.translate("Replace", "Start search from top of the file or selection.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_top.setText(QtGui.QApplication.translate("Replace", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bottom.setToolTip(QtGui.QApplication.translate("Replace", "Start search from the bottom of the file or selection.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_bottom.setText(QtGui.QApplication.translate("Replace", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_replace.setText(QtGui.QApplication.translate("Replace", "Replace with: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_find.setText(QtGui.QApplication.translate("Replace", "Find: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_mode.setTitle(QtGui.QApplication.translate("Replace", "Search Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_normal.setToolTip(QtGui.QApplication.translate("Replace", "Search for a word or phrase.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_normal.setText(QtGui.QApplication.translate("Replace", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_reference.setToolTip(QtGui.QApplication.translate("Replace", "Search using a regular expression.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_reference.setText(QtGui.QApplication.translate("Replace", "References", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_findops.setTitle(QtGui.QApplication.translate("Replace", "Find In", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_current.setToolTip(QtGui.QApplication.translate("Replace", "Find the text in the file currently selected and displayed in the main tab of the viewer.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_current.setText(QtGui.QApplication.translate("Replace", "Current File", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_selection.setToolTip(QtGui.QApplication.translate("Replace", "Search the currently selected text in the viewer.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_selection.setText(QtGui.QApplication.translate("Replace", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findnext.setToolTip(QtGui.QApplication.translate("Replace", "Go to the next item found [F3].", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findnext.setText(QtGui.QApplication.translate("Replace", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findnext.setShortcut(QtGui.QApplication.translate("Replace", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findprev.setToolTip(QtGui.QApplication.translate("Replace", "Go to the previous find [F4].", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findprev.setText(QtGui.QApplication.translate("Replace", "Find Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findprev.setShortcut(QtGui.QApplication.translate("Replace", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_replace.setToolTip(QtGui.QApplication.translate("Replace", "Replace the currently selected match.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_replace.setText(QtGui.QApplication.translate("Replace", "Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_replaceall.setToolTip(QtGui.QApplication.translate("Replace", "Replace all matches.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_replaceall.setText(QtGui.QApplication.translate("Replace", "Replace All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_count.setToolTip(QtGui.QApplication.translate("Replace", "Displays how many items where found.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_count.setText(QtGui.QApplication.translate("Replace", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_findinfiles.setText(QtGui.QApplication.translate("Replace", "Find in Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_options.setTitle(QtGui.QApplication.translate("Replace", "Search Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_verbatim.setToolTip(QtGui.QApplication.translate("Replace", "Search for exactly what is in the Find text box. Matches that are inside a word or otherwise partial finds are ignored.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_verbatim.setText(QtGui.QApplication.translate("Replace", "Verbatim", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_case.setToolTip(QtGui.QApplication.translate("Replace", "Case sensitive search.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_case.setText(QtGui.QApplication.translate("Replace", "Case", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_wrap.setText(QtGui.QApplication.translate("Replace", "Wrap", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_re.setText(QtGui.QApplication.translate("Replace", "RegExp", None, QtGui.QApplication.UnicodeUTF8))

